# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XlDyGc2Ogv_lci0HZD0R6XNKKLDsKsA
"""

from datetime import date

try:
  diaNacimiento = int(input("Ingrese día de nacimiento: "))
  mesNacimiento = int(input("Ingrese mes de nacimiento: "))
  anioNacimiento = int(input("Ingrese anio de nacimiento: "))

  fechaActual = date.today()
  diaActual = fechaActual.day
  mesActual = fechaActual.month
  anioActual = fechaActual.year

  anios = anios = anioActual - anioNacimiento
  meses = 0
  dias = 0

  if(mesNacimiento > mesActual):
    anios = anios - 1
    meses = mesNacimiento - mesActual
    if(diaNacimiento > diaActual):
      dias = diaNacimiento - diaActual
  elif(mesActual == mesNacimiento):
    if(diaNacimiento > diaActual):
      anios = anios - 1
      dias = diaNacimiento - diaActual
  
  print(f"La edad es {anios} años, {meses} meses y {dias} días.")
  
except Exception as ex:
  print(ex)