# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FXAflobWOMzWAH8CnI6o15CYkkdO5JMF
"""

def obtener_calificacion(nota):
  nota_minima_aprobacion = 71

  if(nota < 50):
    print("INSUFICIENTE")
  elif(50 <= nota and nota <= 60):
    print("REGULAR")
  elif(60 < nota and nota <= 70):
    print("BIEN")
  elif(70 < nota and nota <= 90):
    print("MUY BIEN")
  elif(90 < nota and nota <= 100):
    print("SOBRESALIENTE")
  else:
    print("Nota fuera del rango")

  if(nota < nota_minima_aprobacion):
    print("La diferencia entre la nota de aprobación y la nota ingresada es de: "
    ,nota_minima_aprobacion - nota)

try:
  nota = float(input("Ingrese nota del estudiante: "))

  obtener_calificacion(nota)
except:
  print("Datos incorrectos")