# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gDPcJQR3BROst8FquvSe2hz2_d4ueLYt
"""

try:
  primer_numero = int(input("Ingrese el primer número: "))
  segundo_numero = int(input("Ingrese el segundo número, debe ser menor al primer número: "))

  if(primer_numero <= segundo_numero):
    raise Exception("El Primer Número debe ser mayor que el Segundo")

  rango_numeros = range(primer_numero, segundo_numero-1, -1)
  suma = ""
  
  for numero in rango_numeros:
    if(numero == primer_numero):
      suma += f"{numero}"
    else:
      suma += f"+{numero}"

  suma += f"={sum(rango_numeros)}"

  print(f"La suma es: {suma}")
  
except ValueError:
  print("Datos incorrectos")
except Exception as ex:
  print(ex)