# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4sglr2zXV-4QwbSDtcT08pphrzAq414
"""

try:
  numero = int(input("Ingrese un número: "))

  if(numero <= 0):
    raise Exception("Ingrese un número mayor a 0")

  factores = []

  factor = 1
  while(factor <= numero):
    if((numero % factor) == 0):
      factores.append(factor)
    
    factor +=1

  print(f"Número ingresado: {numero}")
  print(f"Factores: {factores}")

except ValueError:
  print("Ingrese un número")
except Exception as ex:
  print(ex)